Table widget
nuvla/ui pull request #1030
Opened 2022-11-30 20:01 UTC by MTrost

2022-12-06 08:34 UTC, MTrost commented
Solves #1005

2022-12-09 15:10 UTC, 0xbase12 requested changes
Getting blank pages when trying to load edges or deployments pages

2022-12-09 15:10 UTC, 0xbase12 commented on code/src/cljs/sixsq/nuvla/ui/plugins/table.cljs
> +             :or {sort-key field-key}}]
:or map can't use destructured fields of the map itself

2022-12-12 09:00 UTC, 0xbase12 commented
The multi column sort is interesting and well done, but don't know if it's too complicated from UX perspective to our end users.
I propose to ask the team what they think during a demo meeting. 

We can have an option that ask to sort only by one column.

2022-12-12 10:17 UTC, MTrost commented
I was thinking about adding this option but then decided against it, because it would make it even more complicated with additional options.

The multi-column sort currently implemented works the same as in Excel or Google Sheets and isn't even that different from single-column sort, because the last clicked column gets full sort applied.

But it wouldn't be that difficult to make it optional and/or configurable

2022-12-12 11:24 UTC, merged