Nuvlabox playbook - opt-in workflow at creation time
nuvla/ui pull request #763
Opened 2022-01-05 10:54 UTC by cjdcordeiro

closes https://github.com/nuvla/ui/issues/758

2022-01-07 12:24 UTC, 0xbase12 requested changes

2022-01-07 13:22 UTC, cjdcordeiro commented on code/src/cljs/sixsq/nuvla/ui/edge/events.cljs
> +                              #(dispatch [::set-nuvlabox-playbooks-cronjob %])
error msg added

2022-01-07 13:26 UTC, cjdcordeiro commented on code/src/cljs/sixsq/nuvla/ui/edge/views.cljs
> +        playbooks-cronjob          (subscribe [::subs/nuvlabox-playbooks-cronjob])
won't that affect how soon that variable becomes available?
changed anyway

2022-01-10 15:39 UTC, 0xbase12 commented on code/src/cljs/sixsq/nuvla/ui/edge/views.cljs
> +                                     [ui/Popup {:content @playbooks-cronjob
Now that I merge this [PR](https://github.com/nuvla/api-server/commit/c69c9e3344aba25eecd27ad599d75379f9b5079c) this PR need to be fixed

2022-01-12 12:08 UTC, 0xbase12 commented
This pull request can be closed because it's included in the https://github.com/nuvla/ui/pull/766?

2022-01-12 12:42 UTC, cjdcordeiro commented
@0xbase12 yes it can

2022-01-12 13:03 UTC, closed without merging